---
# tasks file for deployer
- name: Install ceph-deploy.
  pip:
    name: ceph-deploy
    virtualenv: "{{ venv }}"
    virtualenv_command: pyvenv

- name: Remove Ceph packages from remote hosts and purge all data.
  command: ceph-deploy purge {{ all_servers }}
  args:
    chdir: /home/{{ ansible_user_id }}/{{ cluster_name }}
  ignore_errors: yes
  tags: teardown

- name: Purge any Ceph data from /var/lib/ceph on workers.
  command: ceph-deploy purgedata {{ all_servers }}
  args: 
    chdir: /home/{{ ansible_user_id }}/{{ cluster_name }}
  ignore_errors: yes
  tags: teardown

- name: Remove authentication keys from the local directory.
  command: ceph-deploy forgetkeys
  args: 
    chdir: /home/{{ ansible_user_id }}/{{ cluster_name }}
  ignore_errors: yes
  tags: teardown

- name: Remove /home/{{ ansible_user_id }}/{{ cluster_name }}.
  file:
    path: /home/{{ ansible_user_id }}/{{ cluster_name }}
    state: absent
  tags: teardown

- name: Create a directory to save configuration and key files.
  file:
    path: /home/{{ ansible_user_id }}/{{ cluster_name }}
    state: directory

- name: Create {{ cluster_name }} ceph cluster.
  command: |
    ceph-deploy new --no-ssh-copykey --public-network {{ public_network }}
    {{ mon_servers }}
  args:
    chdir: /home/{{ ansible_user_id }}/{{ cluster_name }}

- name: Set up ceph monitors.
  include_tasks: mon.yml
  tags: mon_tasks

- name: Set up ceph managers.
  include_tasks: mgr.yml
  tags: mgr_tasks

- name: Set up ceph osds.
  include_tasks: osd.yml
  tags: osd_tasks

- name: Set up ceph mds.
  include_tasks: mds.yml
  tags: mds_tasks

- name: Set up ceph clients.
  include_tasks: client.yml
  tags: client_tasks
...
